//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subli_art_Ludo_Cropper.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_Italian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_Italian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subli_art_Ludo_Cropper.Languages.Lang-Italian", typeof(Lang_Italian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutte le posizioni devono essere approvate.
        /// </summary>
        internal static string All_slots_must_be_full_and_approved {
            get {
                return ResourceManager.GetString("All_slots_must_be_full_and_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma Taglio.
        /// </summary>
        internal static string Approve_Crop {
            get {
                return ResourceManager.GetString("Approve_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se sei soddisfatto delle immagini cliccare sul pulsante sotto.
        /// </summary>
        internal static string Arrow_Text_Create {
            get {
                return ResourceManager.GetString("Arrow_Text_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Arrow_Text_Exit {
            get {
                return ResourceManager.GetString("Arrow_Text_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Arrow_Text_Next {
            get {
                return ResourceManager.GetString("Arrow_Text_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prima di chiudere?.
        /// </summary>
        internal static string before_closing {
            get {
                return ResourceManager.GetString("before_closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rimuovi la Libreria.
        /// </summary>
        internal static string Clear_Library {
            get {
                return ResourceManager.GetString("Clear_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rimuovi Posizione.
        /// </summary>
        internal static string Clear_Slot {
            get {
                return ResourceManager.GetString("Clear_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea PDF.
        /// </summary>
        internal static string Create_PDF {
            get {
                return ResourceManager.GetString("Create_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando PDF....
        /// </summary>
        internal static string Creating_PDF {
            get {
                return ResourceManager.GetString("Creating_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esci.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finito.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa Immagini.
        /// </summary>
        internal static string Import_Images {
            get {
                return ResourceManager.GetString("Import_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prossima.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prossima Posizione.
        /// </summary>
        internal static string Next_Slot {
            get {
                return ResourceManager.GetString("Next_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Aperto.
        /// </summary>
        internal static string Open_PDF {
            get {
                return ResourceManager.GetString("Open_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprire la cartella PDF.
        /// </summary>
        internal static string Open_PDF_Folder {
            get {
                return ResourceManager.GetString("Open_PDF_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzioni.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anteprima Posizione.
        /// </summary>
        internal static string Previous_Slot {
            get {
                return ResourceManager.GetString("Previous_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva Come.
        /// </summary>
        internal static string Save_As {
            get {
                return ResourceManager.GetString("Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvare le modifiche al documento.
        /// </summary>
        internal static string Save_changes_to_document {
            get {
                return ResourceManager.GetString("Save_changes_to_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posizione.
        /// </summary>
        internal static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcune immagini non possono essere trovate.
        /// </summary>
        internal static string Some_images_could_not_be_found {
            get {
                return ResourceManager.GetString("Some_images_could_not_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senza Titolo.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Guida:
        ///
        ///1. Importa le immagini dalla tua libreria usando il tasto “Importa Immagini...”.
        ///2. Ritaglia l’immagine usando lo strumento di ritaglio che apparirà al centro dell’immagine.
        ///3. Approva il ritaglio cliccando sul tasto V e inizia il ritaglio di una nuova immagine.
        ///4. Una volta terminato il lavoro per tutte le immagini, clicca il tasto “Crea PDF” per salvare il documento che contiene il foglio con tutte le mmagini da stampare..
        /// </summary>
        internal static string User_Guide {
            get {
                return ResourceManager.GetString("User_Guide", resourceCulture);
            }
        }
    }
}
