//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subli_art_Ludo_Cropper.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subli_art_Ludo_Cropper.Languages.Lang-English", typeof(Lang_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All slots must be full and approved.
        /// </summary>
        internal static string All_slots_must_be_full_and_approved {
            get {
                return ResourceManager.GetString("All_slots_must_be_full_and_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Crop.
        /// </summary>
        internal static string Approve_Crop {
            get {
                return ResourceManager.GetString("Approve_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are satisfied with your cropping job press the PDF button.
        /// </summary>
        internal static string Arrow_Text_Create {
            get {
                return ResourceManager.GetString("Arrow_Text_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are satisfied with your PDFs press the exit button.
        /// </summary>
        internal static string Arrow_Text_Exit {
            get {
                return ResourceManager.GetString("Arrow_Text_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue cropping the players in the next page.
        /// </summary>
        internal static string Arrow_Text_Next {
            get {
                return ResourceManager.GetString("Arrow_Text_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before closing?.
        /// </summary>
        internal static string before_closing {
            get {
                return ResourceManager.GetString("before_closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        internal static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Library.
        /// </summary>
        internal static string Clear_Library {
            get {
                return ResourceManager.GetString("Clear_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Slot.
        /// </summary>
        internal static string Clear_Slot {
            get {
                return ResourceManager.GetString("Clear_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PDF.
        /// </summary>
        internal static string Create_PDF {
            get {
                return ResourceManager.GetString("Create_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating PDF....
        /// </summary>
        internal static string Creating_PDF {
            get {
                return ResourceManager.GetString("Creating_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Images.
        /// </summary>
        internal static string Import_Images {
            get {
                return ResourceManager.GetString("Import_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Slot.
        /// </summary>
        internal static string Next_Slot {
            get {
                return ResourceManager.GetString("Next_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PDF.
        /// </summary>
        internal static string Open_PDF {
            get {
                return ResourceManager.GetString("Open_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PDF Folder.
        /// </summary>
        internal static string Open_PDF_Folder {
            get {
                return ResourceManager.GetString("Open_PDF_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Slot.
        /// </summary>
        internal static string Previous_Slot {
            get {
                return ResourceManager.GetString("Previous_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string Save_As {
            get {
                return ResourceManager.GetString("Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to document.
        /// </summary>
        internal static string Save_changes_to_document {
            get {
                return ResourceManager.GetString("Save_changes_to_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        internal static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some imags could not be found.
        /// </summary>
        internal static string Some_images_could_not_be_found {
            get {
                return ResourceManager.GetString("Some_images_could_not_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///User&apos;s Guide:
        ///
        ///1. Import Images to the image library using the &apos;Import Images...&apos; button.
        ///2. Crop the image using the crop tool that will appear at the center of the image.
        ///3. Approve your crop by clicking the &apos;V&apos; button, and begin cropping the next image.
        ///4. When you are done, simply click the &apos;Create PDF&apos; button to save a pdf document containing the ludo sheet.
        ///5. When sending the file to be printed: MAKE SURE THAT &quot;fit to frame&quot; IS TICKED OFF or at page sizing &quot;actual size&quot;  is TICKED ON..
        /// </summary>
        internal static string User_Guide {
            get {
                return ResourceManager.GetString("User_Guide", resourceCulture);
            }
        }
    }
}
